name: meetplatter_final
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-80.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.0+1
  path_provider: ^2.0.11
  dio: ^4.0.6
  json_annotation: ^4.6.0
  liquid_swipe: ^3.0.0
  http: ^0.13.5
  contained_tab_bar_view: ^0.8.0
  blurrycontainer: ^1.0.2
  get: ^4.6.5
  auto_size_text: ^3.0.0
  auto_reload: ^1.0.0
  icon_decoration: ^1.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/home.png